nelmio_api_doc:
  documentation:
#    host: api.skeleton.com
    info:
      title: ApiSkeleton
      description: Made with love with Docker, JWT, Nelmio, and SF4
      version: 0.0.1
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Value: Bearer {jwt}'
        name: Authorization
        in: header
      security:
        - Bearer: []
  areas:
    path_patterns: [ ^/(?!_(profiler|wdt|error)|css|images|js|doc) ]