nelmio_api_doc:
  documentation:
    info:
      title: '%app.api.title%'
      description: '%app.api.description%'
      version: '%app.api.version%'
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Value: Bearer {jwt}'
        name: Authorization
        in: header
      security:
        - Bearer: []
  areas:
    path_patterns: [ ^/(?!_(profiler|wdt|error)|css|images|js|doc) ]