#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /auth/login_check

gesdinet_jwt_refresh_token:
  path: /auth/token/refresh
  controller: gesdinet.jwtrefreshtoken:refresh